### ISSUE TITLE
Don't forget to do both stars each day!

### ISSUE THREAD

**Issue by glguy** [jonschoning/advent-of-code-2017#1]
Hi, I was looking through the #haskell leaderboard and I saw you only had part 1 of day 1 finished. Your GitHub repo is sufficiently advanced that I thought that this could be an oversight. Each day has two parts where the second part unlocks after you finish the first!

(If you already knew about this, sorry about the noise)

**Comment by jonschoning** [comment]
yeah got a late start... will do my best, thanks!
